### ISSUE TITLE
Ability to add labels to a PR if there is an error

### ISSUE THREAD

**Issue by brianespinosa** [tibdex/auto-update#2]
Thanks for your work on this and Autosquash!

Are you open to accepting PRs that would extend this further? My guess is you would rather keep this simple, which is fine. If you are open to updates, I would be interested in adding a label or comment to the PR if there were conflicts. It looks as if we are just returning the warning if there is an error trying to update, so that complicates things having to know what all of the possible responses are that we want to handle commenting or labeling.

Let me know if you would prefer to keep this out of this simple implementation and I can fork your work instead to put something together based on my teams needs.

**Comment by tibdex** [comment]
I think a nice behavior would be to have this action comment on PRs that were candidates to being updated but failed to be (e.g. because of conflicts). 

When the action is configured to only target PRs with a specific label, we could also remove this label as an indication that something is blocking the auto update and manual intervention is required.

A new label would thus not be required. 

What do you think?

**Comment by brianespinosa** [comment]
@tibdex the use case I was thinking about here is when looking at a list of PRs, Github does not have a way to see which PRs have conflicts without going in to look at them. I think in this case, maybe my suggestion is better suited as a separate labeler action in the workflow with `auto-update` that would label/remove any labels for having conflicts.

I think your suggestion here potentially better aligns with the scope of what this action is supposed to achieve and does not extend to solving UX issues with Github.

**Comment by tibdex** [comment]
The commit https://github.com/tibdex/auto-update/commit/09a5dc743a90366d0cef41ae316421d4485168d1 implements a behavior similar to what https://github.com/tibdex/auto-update/issues/2#issuecomment-792275428 suggested.
